name: crud
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0  
  path_provider: ^2.1.2
  isar: ^3.1.0
  isar_flutter_libs: any
  shared_preferences: ^2.5.3
  path: ^1.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: any
  build_runner: any
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
